### ISSUE TITLE
Add "Buy" to global nav

### ISSUE THREAD

**Issue by jsonin** [goinvo/CareCards#1]
Should initially go to our Prefundia site:
http://prefundia.com/projects/view/care-cards/5723/

Then once Kickstarter goes live, we'll shoot them to KS.
Finally, once we have them in hand, a link to Amazon.

**Comment by jen-p** [comment]
Link doesn't work. Redirects to http://prefundia.com/

**Comment by jsonin** [comment]
Will get updated URL by Thu 25.Jun (getting "approved").

**Comment by jen-p** [comment]
added
