### ISSUE TITLE
About Section: team list

### ISSUE THREAD

**Issue by jsonin** [goinvo/CareCards#5]
Team

Juhan Sonin
Author, juhan@goinvo.com

Harry Sleeper
Author

Sarah Kaiser
Artist, Lead Illustrator

Jane Kokernak
Editor, Researcher

Emily Twaddell
Editor, Researcher

Jennifer Patel
Designer, Online Presence

Other Contributors
- Beth Herlin, designer, researcher
- Kelly Mansfield, illustrator
- Dirk Knemeyer
- Eric Benoit

**Comment by jen-p** [comment]
added
